name = "shelby/VEST"
version = "0.1.0"
license = "Apache-2.0"
description = "Aiken vesting contract for Cardano"

[repository]
user = "shelby69699"
project = "VEST"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.0.1-beta"
source = "github"
